services:
  vpn-mini-app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - /usr/local/x-ui/bin/config.json:/usr/local/x-ui/bin/config.json
    restart: unless-stopped
