services:
  vpn-mini-app:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - /opt/outline/persisted-state/shadowbox_server_config.json:/opt/outline/persisted-state/shadowbox_server_config.json
      - /opt/outline/persisted-state/shadowbox_config.json:/opt/outline/persisted-state/shadowbox_config.json
    restart: unless-stopped
